source: src

exclude:
  - CNAME
  - LICENSE
  - "README*"
  - .idea

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      styles:
        - "style"

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true
